### ISSUE TITLE
Plugin dependencies

### ISSUE THREAD

**Issue by lukekarrys** [andyet/eslint-config-andyet#2]
In npm3 there is a flatter dependency tree which means when `eslint-plugin-hapi` is installed as a dependency of `eslint-config-andyet` it gets installed at the top level, and is therefore requireable by `eslint`...most of the time.

But if we already have `eslint-plugin-hapi@1` installed and then install `eslint-config-andyet`, then `eslint` will use v1 of the plugin.

Eslint is [aware of this issue](https://github.com/eslint/eslint/issues/3458) and it looks like v2 might solve it next month.
### Example

**package.json**

``` js
"devDependencies": {
  "eslint": "^1.10.3",
  "eslint-config-andyet": "^1.0.0",
  "eslint-plugin-hapi": "^1.2.2"
}
```

**.eslintrc**

```
{
  "extends": "andyet"
}
```

Running `eslint .` on some otherwise error free code then produces this output:

```
> eslint .


/Users/lukekarrys/Desktop/test/index.js
  1:1  error  Definition for rule 'hapi/no-arrowception' was not found  hapi/no-arrowception

✖ 1 problem (1 error, 0 warnings)
```
### Possible Solutions
- Use `peerDependencies`. This would be annoying if we use this repo as a source for multiple configs (frontend, backend, es6, es5, etc). If you only want to lint frontend on a project you will still need to install all the peer dependency plugins for the other config types.
- Use `peerDependencies` and split up the configs to separate repos/packages. This would solve the above issue, but may be be more difficult to maintain.
- Don't specify plugin dependencies and use documentation instead for which plugins you'll need

```
## For backend
npm install eslint-config-andyet eslint-config-hapi ... --save-dev
# For frontend
npm install eslint-config-andyet babel-eslint eslint-plugin-react ... --save-dev
```
- Not worry about it, and instead document that you shoudn't install any conflicting eslint-plugins or configs.

**Comment by lukekarrys** [comment]
> - Not worry about it, and instead document that you shoudn't install any conflicting eslint-plugins or configs.

In thinking about it more and doing some testing, this could also happen if another dependency (not just the root project) specifies a different version of `eslint-plugin-hapi`.

If two dependencies specify different versions of something whichever one is installed first will sit at the top level of `node_modules`. So just documenting doesn't seem like a good solution since it can be caused by subdependencies too.

**Comment by latentflip** [comment]
Something I'm a bit confused about:

If our config wants `eslint-plugin-hapi@2` and some other module wants `eslint-plugin-hapi@1`, will things not potentially break no matter how we set it up, because eslint will only load one version, and the thing that depends on the other will potentially break?

I can see there's still an issue where you started with one config, and move to another, and you need to reboot node_modules before things are `fixed`. And I guess there's the chance of some module accidentally listing a plugin as a dependency, instead of a devdep?
